### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by flexxxxer** [smolpaw/ambient-mode-blocker#1]
Just not working. Firefox 109.0

**Comment by loufee** [comment]
Seems to be working for me in both normal and private window. The 'ambient mode' toggle is not present. FF 109.0.

**Comment by dragonxp** [comment]
> 

Can you check for v115 ? It never stopped working for me

**Comment by smolpaw** [comment]
> Just not working. Firefox 109.0

Can you check for v115 ? It never stopped working for me

**Comment by smolpaw** [comment]
> Just not working. Firefox 109.0

Can you check now with the new version ?
Make sure you have the up to date version installed : https://addons.mozilla.org/en-US/firefox/addon/ambient-mode-blocker/

**Comment by smolpaw** [comment]
Closing the issue due to inactivity from the Author.
The issue is likely fixed.
