### ISSUE TITLE
Firefox 115 Not Working

### ISSUE THREAD

**Issue by ItsRogueRen** [smolpaw/ambient-mode-blocker#2]
Using this on FF 115 leads to the ambient mode switch shill being on and still accessible in the YouTube player. Running on Linux Pop!_OS 22.04 LTS (Ubuntu based)

**Comment by smolpaw** [comment]
> Using this on FF 115 leads to the ambient mode switch shill being on and still accessible in the YouTube player. Running on Linux Pop!_OS 22.04 LTS (Ubuntu based)

It never stopped working for my Win FF. I will test and push a fix for Ubuntu

**Comment by smolpaw** [comment]
> Using this on FF 115 leads to the ambient mode switch shill being on and still accessible in the YouTube player. Running on Linux Pop!_OS 22.04 LTS (Ubuntu based)

Could you check again with the new version ?
I have updated the extension in the firefox addons store.

**Comment by ItsRogueRen** [comment]
> > Using this on FF 115 leads to the ambient mode switch shill being on and still accessible in the YouTube player. Running on Linux Pop!_OS 22.04 LTS (Ubuntu based)
> 
> Could you check again with the new version ? I have updated the extension in the firefox addons store.

Nothing has changed for me on the latest FF and the newest install of the add-on from the FF store. Ambient mode is always enabled and I have manually turn it off.

**Comment by ItsRogueRen** [comment]
> > > Using this on FF 115 leads to the ambient mode switch shill being on and still accessible in the YouTube player. Running on Linux Pop!_OS 22.04 LTS (Ubuntu based)
> > 
> > 
> > Could you check again with the new version ? I have updated the extension in the firefox addons store.
> 
> Nothing has changed for me on the latest FF and the newest install of the add-on from the FF store. Ambient mode is always enabled and I have manually turn it off.

NEVERMIND! I had to completely restart the browser but it does seem to work now

**Comment by ItsRogueRen** [comment]
Might have been a bit too hasty here. The plugin does work, but only after I reload a page after opening it. It doesn't turn off Ambient mode the first time.

**Comment by smolpaw** [comment]
> Might have been a bit too hasty here. The plugin does work, but only after I reload a page after opening it. It doesn't turn off Ambient mode the first time.

Thanks for pointing that out.
Didn't notice youtube switched to a single-page application so the script wasn't getting fired at all if the first visit was to the root domain or when switching pages.
Download v2.1 and let me know if the issue still persists : https://addons.mozilla.org/en-US/firefox/addon/ambient-mode-blocker/

**Comment by ItsRogueRen** [comment]
> > Might have been a bit too hasty here. The plugin does work, but only after I reload a page after opening it. It doesn't turn off Ambient mode the first time.
> 
> Thanks for pointing that out.
> Didn't notice youtube switched to a single-page application so the script wasn't getting fired at all if the first visit was to the root domain or when switching pages.
> Download v2.1 and let me know if the issue still persists : https://addons.mozilla.org/en-US/firefox/addon/ambient-mode-blocker/

2.1 seems to have done the trick!
